### ISSUE TITLE
Epic: BigQuery updates and improvements

### ISSUE THREAD

**Issue by baldm0mma** [grafana/google-bigquery-datasource#185]
An epic for tracking ongoing enhancements to the Google BigQuery Datasource
Making BigQuery Datasource multitenant capable [documentation](https://docs.google.com/document/d/1Lm76T1U0TE4tIoA274l3aFUqW3medn2rzZzBplQQgT4/edit#heading=h.jd7x3o9z9tn0).
### Enhancements

- [x] grafana/google-bigquery-datasource#187
- [x] grafana/google-bigquery-datasource#183

### Support/Escalations

- [x] [breaking changes migration docs](https://github.com/grafana/support-escalations/issues/6201)
- [x] grafana/google-bigquery-datasource#184

### Bugs

- [ ] #

### Community conversation

- [ ] #

### Multi-tenancy

- [ ] https://github.com/grafana/google-bigquery-datasource/pull/177
